In [1]:
import numpy as np

### np.hstack(<span style='color:red'>(</span>a,b<span style='color:red'>)</span>),  np.c_<span style='color:red'>[</span>a,b<span style='color:red'>]</span> 
오른쪽으로 이어가기 (소괄호((), 대괄[]호 유의)

In [2]:
a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([7, 8, 9])
br = b.reshape(3,1)

In [3]:
print('a.ndim : {}, a.shape : {}'.format(a.ndim, a.shape))
print('b.ndim : {}, b.shape : {}'.format(b.ndim, b.shape))
print('br.ndim : {}, br.shape : {}'.format(br.ndim, br.shape))

a.ndim : 2, a.shape : (3, 2)
b.ndim : 1, b.shape : (3,)
br.ndim : 2, br.shape : (3, 1)


In [4]:
np.hstack((a,br)) # ndim일치 및 shape 일치후

array([[1, 2, 7],
       [3, 4, 8],
       [5, 6, 9]])

In [5]:
np.c_[a,b] # ndim과 관계없이 같은 방향으로만 shape가 일치하면 됨.

array([[1, 2, 7],
       [3, 4, 8],
       [5, 6, 9]])

In [6]:
np.c_[a, b, a, b]

array([[1, 2, 7, 1, 2, 7],
       [3, 4, 8, 3, 4, 8],
       [5, 6, 9, 5, 6, 9]])

### np.vstack(<span style='color:red'>(</span>a,b<span style='color:red'>)</span>),  np.r_<span style='color:red'>[</span>a,b<span style='color:red'>]</span> 
아래쪽으로 이어가기 (소괄호((), 대괄[]호 유의)

In [7]:
a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([7, 8])
br = b.reshape(1,2)

In [8]:
a, b, br

(array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([7, 8]),
 array([[7, 8]]))

In [9]:
print('a.ndim : {}, a.shape : {}'.format(a.ndim, a.shape))
print('b.ndim : {}, b.shape : {}'.format(b.ndim, b.shape))
print('br.ndim : {}, br.shape : {}'.format(br.ndim, br.shape))

a.ndim : 2, a.shape : (3, 2)
b.ndim : 1, b.shape : (2,)
br.ndim : 2, br.shape : (1, 2)


In [10]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [11]:
np.vstack((a,br))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [12]:
np.r_[a, br] # row 축 shape일치 (1, 2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

### np.concatinate(<span style='color:red'>(</span>a,b<span style='color:red'>)</span>, axis=(<span style='color:red'>0</span>) : 아래쪽으로 붙이기
### np.concatinate(<span style='color:red'>(</span>a,b<span style='color:red'>)</span>, axis=(<span style='color:red'>1</span>) : 오른쪽으로 붙이기
.ndim, .shape가 일치해야 함.

In [13]:
a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([7, 8])
bc = np.array([9, 10, 11])
br = b.reshape(1,2)
c = np.array([12, 13])
cr = c.reshape(1,2)

In [14]:
a, b, bc, br, c, cr

(array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([7, 8]),
 array([ 9, 10, 11]),
 array([[7, 8]]),
 array([12, 13]),
 array([[12, 13]]))

In [15]:
print('a.ndim : {}, a.shape : {}'.format(a.ndim, a.shape))
print('b.ndim : {}, b.shape : {}'.format(b.ndim, b.shape))
print('bc.ndim : {}, bc.shape : {}'.format(bc.ndim, bc.shape))
print('br.ndim : {}, br.shape : {}'.format(br.ndim, br.shape))
print('c.ndim : {}, c.shape : {}'.format(c.ndim, c.shape))
print('cr.ndim : {}, cr.shape : {}'.format(cr.ndim, cr.shape))

a.ndim : 2, a.shape : (3, 2)
b.ndim : 1, b.shape : (2,)
bc.ndim : 1, bc.shape : (3,)
br.ndim : 2, br.shape : (1, 2)
c.ndim : 1, c.shape : (2,)
cr.ndim : 2, cr.shape : (1, 2)


In [16]:
np.concatenate((a,br), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [17]:
np.concatenate((a, bc.reshape(3,1)), axis=1)  # shape를 맞춰야 함.

array([[ 1,  2,  9],
       [ 3,  4, 10],
       [ 5,  6, 11]])

In [18]:
np.concatenate((b, c), axis=0)

array([ 7,  8, 12, 13])

In [19]:
np.concatenate((br, cr), axis=1)

array([[ 7,  8, 12, 13]])

In [20]:
np.concatenate((br, cr), axis=0)

array([[ 7,  8],
       [12, 13]])

In [21]:
np.concatenate((br.reshape(2,1), cr.reshape(2,1)), axis=1)  # 행 벡터 오른쪽으로 합치기

array([[ 7, 12],
       [ 8, 13]])

### np.column_stack(<span style='color:red'>(</span>a,b<span style='color:red'>)</span>)
column 벡터 오른쪽으로 이어가기
== np.c_[a, b]

In [22]:
a = np.array([1,2,3]).reshape(3,1)
b = np.array([4,5,6]).reshape(3,1)
a, b

(array([[1],
        [2],
        [3]]),
 array([[4],
        [5],
        [6]]))

In [23]:
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [24]:
aa = np.array([[1, 2], [3, 4], [5, 6]])

In [25]:
np.column_stack((a,b, aa))

array([[1, 4, 1, 2],
       [2, 5, 3, 4],
       [3, 6, 5, 6]])

In [26]:
np.c_[a,b,aa]

array([[1, 4, 1, 2],
       [2, 5, 3, 4],
       [3, 6, 5, 6]])

### np.row_stack(<span style='color:red'>(</span>a,b<span style='color:red'>)</span>)
row 벡터 오른쪽으로 이어가기
== np.r_[a, b] .shape변환후 사용해야 함.

In [27]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a, b

(array([1, 2, 3]), array([4, 5, 6]))

In [28]:
np.row_stack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
np.r_[a,b] # 원하는 결과가 아닌 횡으로 합쳐짐.

array([1, 2, 3, 4, 5, 6])

In [30]:
np.r_[a.reshape(1,3),b.reshape(1,3)] #shape 변환후 사용해야 함.

array([[1, 2, 3],
       [4, 5, 6]])